--- #YAML:1.0
name:               Zack
version:            1.08
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1
    Cwd:                  3
    English:              1.02
    Exporter:             5
    File::Basename:       2.74
    File::Path:           1.08
    File::Spec::Functions:  3.2701
    File::Which:          0.05
    Getopt::Long:         2.35
    Getopt::Std::Strict:  1.01
    Image::OCR::Tesseract:  1.20
    LEOCHARRE::Class2:    1.13
    LEOCHARRE::CLI:       1.19
    LEOCHARRE::DEBUG:     1.13
    LEOCHARRE::Dir:       1.07
    LEOCHARRE::HTML::Text:  1.03
    LEOCHARRE::Test:      1.09
    PDF::OCR2:            1.01
    Pod::Usage:           1.33
    Readonly:             1.03
    RTF::TEXT::Converter:  0
    Smart::Comments:      1
    Spreadsheet::ParseExcel:  0.33
    Test::Simple:         0
    XML::Simple:          2.18
    YAML:                 0.66
    YAML::DBH:            1.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
